#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""UltraBalloonDB V00J1 G1/G2 rule-exception reconstruction core.

G1 = compact deterministic rule/model.
G2 = exceptions/residual needed to rebuild the original bytes exactly.
G5 = validation/audit: original SHA256 == rebuilt SHA256.

This module is deliberately small. It is not a universal compressor and does not
claim wins on random/encrypted/already-compressed bytes. It proves the core
contract for structural datasets: rebuild is byte-for-byte exact while the hot
model remains queryable.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import zlib
from typing import Dict, Iterable, List, Tuple

VERSION = "V00J1_G1G2_RULE_EXCEPTION_RECONSTRUCTION_CORE"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


def canon(obj: object) -> bytes:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def _splitmix64(x: int) -> int:
    x = (x + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
    return (z ^ (z >> 31)) & 0xFFFFFFFFFFFFFFFF


def formula_bit(i: int, j: int, salt: int = 0xB41100DB) -> int:
    """A deterministic compact rule that produces high-entropy-looking bits.

    The point is structural reconstruction: a tiny rule can rebuild a large
    byte stream exactly. The generated bytes are intentionally hostile to zlib,
    so this tests rule compression rather than repeated-byte compression.
    """
    x = ((i & 0xFFFFFFFF) << 32) ^ (j & 0xFFFFFFFF) ^ salt
    return (_splitmix64(x) >> 63) & 1


def deterministic_exception_pairs(n: int, count: int) -> List[Tuple[int, int]]:
    seen = set()
    out: List[Tuple[int, int]] = []
    k = 0
    while len(out) < count:
        i = _splitmix64(0xA5A5A5A5 ^ k) % n
        j = _splitmix64(0x5A5A5A5A ^ (k * 17 + 3)) % n
        pair = (int(i), int(j))
        if pair not in seen:
            seen.add(pair)
            out.append(pair)
        k += 1
    out.sort()
    return out


def _formula_byte(byte_index: int, salt: int = 0xB41100DB) -> int:
    return _splitmix64((byte_index ^ salt) & 0xFFFFFFFFFFFFFFFF) & 0xFF


def build_rule_matrix_bytes(n: int, exceptions: Iterable[Tuple[int, int]]) -> bytes:
    # Byte-level deterministic rule: much faster than per-cell object decode,
    # while still representing an n*n bit matrix in row-major bit order.
    bit_count = n * n
    out = bytearray((bit_count + 7) // 8)
    for byte_index in range(len(out)):
        out[byte_index] = _formula_byte(byte_index)

    # G2 residual: sparse bit flips over the rule-generated matrix.
    for i, j in exceptions:
        bit_index = int(i) * n + int(j)
        if 0 <= bit_index < bit_count:
            out[bit_index >> 3] ^= 1 << (bit_index & 7)
    return bytes(out)


def make_low_exception_graph_package(n: int, exception_count: int) -> Dict[str, object]:
    exceptions = deterministic_exception_pairs(n, exception_count)
    original = build_rule_matrix_bytes(n, exceptions)
    package = {
        "version": VERSION,
        "kind": "LOW_EXCEPTION_RULE_MATRIX",
        "g1": {
            "model": "splitmix64_formula_bit_matrix_v1",
            "n": n,
            "salt_hex": "B41100DB",
            "bit_order": "row_major_lsb0",
        },
        "g2": {
            "exception_count": len(exceptions),
            "flip_pairs": exceptions,
        },
        "g3": {
            "queryable_structure": True,
            "supports_cell_query": True,
            "supports_exception_lookup": True,
        },
        "g4": {
            "patch_layer_present": False,
        },
        "g5": {
            "original_sha256": sha256_bytes(original),
            "lossless_rebuild_required": True,
        },
    }
    rebuilt = rebuild_low_exception_graph(package)
    encoded = canon(package)
    return _dataset_report("low_exception_rule_matrix", original, encoded, rebuilt, package)


def rebuild_low_exception_graph(package: Dict[str, object]) -> bytes:
    g1 = package["g1"]
    g2 = package["g2"]
    if g1.get("model") != "splitmix64_formula_bit_matrix_v1":
        raise ValueError("unsupported G1 model")
    n = int(g1["n"])
    exceptions = [tuple(map(int, p)) for p in g2.get("flip_pairs", [])]
    return build_rule_matrix_bytes(n, exceptions)


def make_prefix_id_original(record_count: int) -> Tuple[bytes, Dict[int, str]]:
    exceptions: Dict[int, str] = {}
    rows: List[str] = []
    prefix = "9606.ENSP"
    for i in range(record_count):
        if i % 997 == 251:
            value = f"CUSTOM.ALT{(i * 7919) % 100000000:08d}"
            exceptions[i] = value
        else:
            value = f"{prefix}{i:011d}"
        rows.append(value)
    return ("\n".join(rows) + "\n").encode("utf-8"), exceptions


def make_prefix_id_package(record_count: int) -> Dict[str, object]:
    original, exceptions = make_prefix_id_original(record_count)
    package = {
        "version": VERSION,
        "kind": "PREFIX_ID_FAMILY",
        "g1": {
            "template": "{prefix}{index:011d}",
            "prefix": "9606.ENSP",
            "record_count": record_count,
            "separator": "\\n",
            "encoding": "utf-8",
        },
        "g2": {
            "exception_count": len(exceptions),
            "value_overrides": exceptions,
        },
        "g3": {
            "queryable_structure": True,
            "supports_prefix_query": True,
            "supports_index_to_record": True,
        },
        "g4": {
            "patch_layer_present": False,
        },
        "g5": {
            "original_sha256": sha256_bytes(original),
            "lossless_rebuild_required": True,
        },
    }
    rebuilt = rebuild_prefix_id_family(package)
    encoded = canon(package)
    return _dataset_report("prefix_id_family", original, encoded, rebuilt, package)


def rebuild_prefix_id_family(package: Dict[str, object]) -> bytes:
    g1 = package["g1"]
    g2 = package["g2"]
    prefix = str(g1["prefix"])
    record_count = int(g1["record_count"])
    overrides = {int(k): str(v) for k, v in g2.get("value_overrides", {}).items()}
    rows: List[str] = []
    for i in range(record_count):
        if i in overrides:
            rows.append(overrides[i])
        else:
            rows.append(f"{prefix}{i:011d}")
    return ("\n".join(rows) + "\n").encode("utf-8")


def deterministic_noise(n: int) -> bytes:
    out = bytearray()
    counter = 0
    seed = b"UltraBalloonDB_V00J1_negative_control"
    while len(out) < n:
        out.extend(hashlib.sha256(seed + counter.to_bytes(8, "little")).digest())
        counter += 1
    return bytes(out[:n])


def negative_random_control(byte_count: int) -> Dict[str, object]:
    original = deterministic_noise(byte_count)
    # The honest path for high-entropy data is to refuse a structural-compression
    # claim. A raw-store fallback is possible, but it is not a compression win.
    raw_store_package = {
        "version": VERSION,
        "kind": "NEGATIVE_RANDOM_CONTROL_RAW_STORE_ONLY",
        "g1": {"model": "none_detected"},
        "g2": {"raw_sha256": sha256_bytes(original), "raw_size_bytes": len(original)},
        "g5": {"compression_claim_allowed": False},
    }
    encoded = canon(raw_store_package)
    raw_store_estimated_bytes = len(original) + len(encoded)
    zlib_bytes = zlib.compress(original, 9)
    return {
        "dataset": "negative_random_control",
        "original_bytes": len(original),
        "g1g2_bytes": raw_store_estimated_bytes,
        "zlib_bytes": len(zlib_bytes),
        "g1g2_ratio": len(original) / max(1, raw_store_estimated_bytes),
        "zlib_ratio": len(original) / max(1, len(zlib_bytes)),
        "compression_claim_allowed": False,
        "random_data_not_falsely_compressed": True,
        "original_sha256": sha256_bytes(original),
    }


def _dataset_report(name: str, original: bytes, encoded: bytes, rebuilt: bytes, package: Dict[str, object]) -> Dict[str, object]:
    original_sha = sha256_bytes(original)
    rebuilt_sha = sha256_bytes(rebuilt)
    zlib_bytes = zlib.compress(original, 9)
    return {
        "dataset": name,
        "original_bytes": len(original),
        "g1g2_bytes": len(encoded),
        "zlib_bytes": len(zlib_bytes),
        "g1g2_ratio": len(original) / max(1, len(encoded)),
        "zlib_ratio": len(original) / max(1, len(zlib_bytes)),
        "beats_zlib_ratio": (len(original) / max(1, len(encoded))) > (len(original) / max(1, len(zlib_bytes))),
        "original_sha256": original_sha,
        "rebuilt_sha256": rebuilt_sha,
        "rebuild_sha256_match": original_sha == rebuilt_sha,
        "queryable_structure_retained": bool(package.get("g3", {}).get("queryable_structure")),
        "package_kind": package.get("kind"),
    }
