#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import heapq
import json
import math
import os
from pathlib import Path
import statistics
import sys
import time
import tracemalloc
from typing import Dict, Iterable, List, Tuple

SCRIPT_PATH = Path(__file__).resolve()
PYTHON_REF = SCRIPT_PATH.parents[2]
if str(PYTHON_REF) not in sys.path:
    sys.path.insert(0, str(PYTHON_REF))

from ultraballoondb_core.attenuation import (  # noqa: E402
    BLOCKING_EDGE_TYPE,
    EDGE_TYPE_NAMES,
    EdgeAttenuationTable,
    all_default_tables,
    compile_edge_mask,
)

STATUS_LINE = "PASS_ULTRABALLOONDB_EDGE_ATTENUATION_TABLE_V00C"
SCHEMA = "ULTRABALLOONDB_V00C_EDGE_ATTENUATION_TABLE_REPORT"

NON_BLOCK_EDGE_TYPES = tuple(name for name in EDGE_TYPE_NAMES if name != BLOCKING_EDGE_TYPE)
ALL_MASK = compile_edge_mask(NON_BLOCK_EDGE_TYPES)
CODE_PROJECT_MASK = compile_edge_mask((
    "UP_RULE",
    "PROJECT_CONTEXT",
    "CODE_PATTERN",
    "RULE_TO_CODE_PATTERN",
    "CODE_TO_RECENT_RULE",
))
PROJECT_ONLY_MASK = compile_edge_mask(("PROJECT_CONTEXT", "PROJECT_TO_RECENT_SEED"))


class SyntheticTypedGraph:
    """Deterministic generated graph for V00C attenuation benchmarking.

    The graph is generated by arithmetic rules, so V00C can benchmark the
    attenuation table without payload I/O or archive rebuild cost.
    """

    def __init__(self, event_count: int) -> None:
        if event_count < 128:
            raise ValueError("event_count must be >= 128")
        self.event_count = int(event_count)
        self.project_count = min(self.event_count, 4096)
        self.recent_count = min(self.event_count, 8192)
        self.rule_base = self.event_count
        self.code_base = self.event_count * 2
        self.project_base = self.event_count * 3
        self.recent_base = self.event_count * 4
        self.logical_node_upper_bound = self.event_count * 4 + self.recent_count

    def edges_for(self, node: int) -> Tuple[Tuple[int, str], ...]:
        n = self.event_count
        if 0 <= node < n:
            e = node
            project_node = self.project_base + (e % self.project_count)
            code_node = self.code_base + e
            rule_node = self.rule_base + e
            lateral_node = (e * 1103515245 + 12345) % n
            blocked_node = self.recent_base + (e % self.recent_count)
            if e % 97 == 0:
                return (
                    (rule_node, "UP_RULE"),
                    (project_node, "PROJECT_CONTEXT"),
                    (code_node, "CODE_PATTERN"),
                    (lateral_node, "LATERAL_SIMILAR_CASE"),
                    (blocked_node, BLOCKING_EDGE_TYPE),
                    (blocked_node, "PROJECT_TO_RECENT_SEED"),
                )
            return (
                (rule_node, "UP_RULE"),
                (project_node, "PROJECT_CONTEXT"),
                (code_node, "CODE_PATTERN"),
                (lateral_node, "LATERAL_SIMILAR_CASE"),
            )
        if self.rule_base <= node < self.code_base:
            e = node - self.rule_base
            return (
                (e, "DOWN_EVIDENCE"),
                (self.code_base + e, "RULE_TO_CODE_PATTERN"),
                ((e * 31 + 7) % n, "RULE_TO_EVIDENCE"),
            )
        if self.code_base <= node < self.project_base:
            e = node - self.code_base
            return ((self.rule_base + ((e * 31 + 7) % n), "CODE_TO_RECENT_RULE"),)
        if self.project_base <= node < self.project_base + self.project_count:
            p = node - self.project_base
            return ((p * 97 % n, "PROJECT_TO_RECENT_SEED"),)
        return ()


def percentile(values: List[float], pct: float) -> float:
    if not values:
        return 0.0
    values_sorted = sorted(values)
    idx = int(math.ceil((pct / 100.0) * len(values_sorted))) - 1
    idx = max(0, min(idx, len(values_sorted) - 1))
    return float(values_sorted[idx])


def deterministic_seeds(event_count: int, sample_count: int) -> List[int]:
    out: List[int] = []
    x = 0xC0FFEE
    for _ in range(sample_count):
        x = (1664525 * x + 1013904223) & 0xFFFFFFFF
        out.append(x % event_count)
    return out


def wave_activation_generated(
    graph: SyntheticTypedGraph,
    seed_node: int,
    table: EdgeAttenuationTable,
    edge_mask: frozenset[str],
    energy_threshold: float,
    top_k: int,
    max_steps: int,
    rigor_multiplier: float,
) -> Tuple[List[Dict[str, object]], Dict[str, int]]:
    if top_k <= 0:
        raise ValueError("top_k must be positive")
    if max_steps < 0:
        raise ValueError("max_steps must be non-negative")
    if not (0.0 <= energy_threshold <= 1.0):
        raise ValueError("energy_threshold must be in [0,1]")
    if rigor_multiplier <= 0.0:
        raise ValueError("rigor_multiplier must be positive")

    best_energy: Dict[int, float] = {seed_node: 1.0}
    best_path: Dict[int, Tuple[str, ...]] = {seed_node: tuple()}
    best_len: Dict[int, int] = {seed_node: 0}
    heap: List[Tuple[float, int, int, Tuple[str, ...]]] = [(-1.0, seed_node, 0, tuple())]
    blocked_path_count = 0
    expanded_edge_count = 0

    while heap:
        neg_energy, node, steps, path = heapq.heappop(heap)
        energy = -neg_energy
        if energy + 1e-18 < best_energy.get(node, 0.0):
            continue
        if steps >= max_steps:
            continue
        edges = graph.edges_for(node)
        blocked_targets = {dst for dst, edge_type in edges if edge_type == BLOCKING_EDGE_TYPE}
        for dst, edge_type in edges:
            expanded_edge_count += 1
            if edge_type == BLOCKING_EDGE_TYPE:
                blocked_path_count += 1
                continue
            if dst in blocked_targets:
                blocked_path_count += 1
                continue
            if edge_type not in edge_mask:
                continue
            atten = min(1.0, table.attenuation(edge_type) * rigor_multiplier)
            if atten <= 0.0:
                continue
            next_energy = energy * atten
            if next_energy < energy_threshold:
                continue
            previous = best_energy.get(dst, -1.0)
            next_path = path + (edge_type,)
            if (next_energy > previous + 1e-18) or (abs(next_energy - previous) <= 1e-18 and (steps + 1, next_path, dst) < (best_len.get(dst, 10**9), best_path.get(dst, tuple()), dst)):
                best_energy[dst] = next_energy
                best_path[dst] = next_path
                best_len[dst] = steps + 1
                heapq.heappush(heap, (-next_energy, dst, steps + 1, next_path))

    rows: List[Dict[str, object]] = []
    for node, energy in best_energy.items():
        if node == seed_node:
            continue
        if energy < energy_threshold:
            continue
        rows.append({
            "node_id": int(node),
            "energy_score": round(float(energy), 12),
            "best_path_len": int(best_len[node]),
            "path_edge_types": list(best_path[node]),
            "record_id_if_available": None,
        })
    rows.sort(key=lambda r: (-float(r["energy_score"]), int(r["best_path_len"]), int(r["node_id"]), tuple(r["path_edge_types"])))
    return rows[:top_k], {"blocked_path_count": blocked_path_count, "expanded_edge_count": expanded_edge_count}


def signature(rows: List[Dict[str, object]]) -> Tuple[Tuple[int, float, Tuple[str, ...]], ...]:
    return tuple((int(r["node_id"]), float(r["energy_score"]), tuple(r["path_edge_types"])) for r in rows)


def scan_new_files_for_call_markers(repo_root: Path) -> Dict[str, object]:
    target_files = [
        repo_root / "python_ref" / "ultraballoondb_core" / "attenuation.py",
        repo_root / "python_ref" / "ultraballoondb_core" / "selftest" / "run_edge_attenuation_table_v00c.py",
        repo_root / "docs" / "V00C_EDGE_ATTENUATION_TABLE.md",
        repo_root / "scripts" / "windows" / "RUN_EDGE_ATTENUATION_TABLE_V00C.ps1",
    ]
    forbidden_markers = tuple([
        "import " + "socket",
        "import " + "requests",
        "urllib" + ".request",
        "http" + "://",
        "https" + "://",
        "api" + "_key",
        "chat" + ".completions",
        "model" + "=",
    ])
    hits = []
    for path in target_files:
        if not path.exists():
            hits.append({"path": str(path), "marker": "MISSING_FILE"})
            continue
        text = path.read_text(encoding="utf-8", errors="replace").lower()
        for marker in forbidden_markers:
            if marker in text:
                hits.append({"path": str(path), "marker": marker})
    return {"checked_files": [str(p) for p in target_files], "hits": hits, "passed": not hits}


def run_benchmark_for_size(event_count: int, recall_samples: int) -> Dict[str, object]:
    t0 = time.perf_counter()
    graph = SyntheticTypedGraph(event_count)
    # Touch deterministic metadata so the build phase cannot be optimized away.
    build_checksum = (graph.logical_node_upper_bound ^ graph.project_count ^ graph.recent_count) & 0xFFFFFFFF
    build_s = max(time.perf_counter() - t0, 1e-9)

    seeds = deterministic_seeds(event_count, min(recall_samples, event_count))
    profiles = {
        "strict_code_project": (EdgeAttenuationTable.from_profile("STRICT_V00C"), CODE_PROJECT_MASK, 0.030, 32, 3, 0.85),
        "balanced_mixed": (EdgeAttenuationTable.from_profile("BALANCED_V00C"), ALL_MASK, 0.020, 64, 3, 1.00),
        "explorative_mixed": (EdgeAttenuationTable.from_profile("EXPLORATIVE_V00C"), ALL_MASK, 0.010, 128, 4, 1.10),
    }
    profile_reports: Dict[str, object] = {}
    for name, (table, mask, threshold, top_k, max_steps, rigor) in profiles.items():
        lat_us: List[float] = []
        returned_counts: List[int] = []
        blocked_counts: List[int] = []
        expanded_counts: List[int] = []
        for seed in seeds:
            q0 = time.perf_counter_ns()
            rows, stats = wave_activation_generated(graph, seed, table, mask, threshold, top_k, max_steps, rigor)
            q1 = time.perf_counter_ns()
            lat_us.append((q1 - q0) / 1000.0)
            returned_counts.append(len(rows))
            blocked_counts.append(int(stats["blocked_path_count"]))
            expanded_counts.append(int(stats["expanded_edge_count"]))
            if len(rows) > top_k:
                raise AssertionError("top_k exceeded")
            if any(float(r["energy_score"]) < threshold for r in rows):
                raise AssertionError("energy threshold violation")
        profile_reports[name] = {
            "profile_hash": table.stable_hash(),
            "energy_threshold": threshold,
            "top_k": top_k,
            "max_steps": max_steps,
            "rigor_multiplier": rigor,
            "wave_latency_median_us": round(statistics.median(lat_us), 3),
            "wave_latency_p95_us": round(percentile(lat_us, 95), 3),
            "wave_latency_p99_us": round(percentile(lat_us, 99), 3),
            "returned_nodes_median": round(statistics.median(returned_counts), 3),
            "returned_nodes_p95": round(percentile([float(x) for x in returned_counts], 95), 3),
            "blocked_path_count_total": int(sum(blocked_counts)),
            "expanded_edge_count_total": int(sum(expanded_counts)),
            "top_k_cap_respected": True,
            "energy_threshold_respected": True,
        }
    return {
        "event_count": event_count,
        "synthetic_logical_node_upper_bound": graph.logical_node_upper_bound,
        "graph_build_events_per_s": round(event_count / build_s, 3),
        "build_checksum": build_checksum,
        "profiles": profile_reports,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--event-sizes", default="10000,100000,1000000")
    parser.add_argument("--recall-samples", type=int, default=1000)
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    if not repo_root.exists():
        raise SystemExit(f"NO_GO_REPO_ROOT_NOT_FOUND: {repo_root}")
    if args.recall_samples <= 0:
        raise SystemExit("NO_GO_RECALL_SAMPLES_MUST_BE_POSITIVE")
    event_sizes = [int(x.strip()) for x in args.event_sizes.split(",") if x.strip()]
    if not event_sizes:
        raise SystemExit("NO_GO_EVENT_SIZES_EMPTY")

    run_id = time.strftime("RUN_%Y%m%d_%H%M%S")
    audit_dir = repo_root / "audit" / "v00c_edge_attenuation_table" / run_id
    audit_dir.mkdir(parents=True, exist_ok=True)

    tracemalloc.start()
    checks: Dict[str, object] = {}

    tables = all_default_tables()
    table_hashes = {table.profile_name: table.stable_hash() for table in tables}
    checks["all_profiles_validate"] = True
    checks["profile_hashes_distinct"] = len(set(table_hashes.values())) == len(table_hashes)

    balanced = EdgeAttenuationTable.from_profile("BALANCED_V00C")
    json_roundtrip = EdgeAttenuationTable.from_json_text(balanced.to_json_text())
    checks["json_roundtrip_stable"] = balanced.stable_hash() == json_roundtrip.stable_hash()

    test_graph = SyntheticTypedGraph(max(10000, min(max(event_sizes), 100000)))
    rows_a, stats_a = wave_activation_generated(test_graph, 1234, balanced, ALL_MASK, 0.02, 64, 3, 1.0)
    rows_b, stats_b = wave_activation_generated(test_graph, 1234, balanced, ALL_MASK, 0.02, 64, 3, 1.0)
    checks["deterministic_results_stable"] = signature(rows_a) == signature(rows_b) and stats_a == stats_b
    checks["top_k_never_exceeded"] = len(rows_a) <= 64
    checks["energy_threshold_applied"] = all(float(r["energy_score"]) >= 0.02 for r in rows_a)

    blocked_rows, blocked_stats = wave_activation_generated(test_graph, 0, balanced, ALL_MASK, 0.0001, 128, 1, 1.0)
    blocked_target = test_graph.recent_base + 0
    checks["is_not_edge_blocks_propagation"] = blocked_target not in {int(r["node_id"]) for r in blocked_rows} and int(blocked_stats["blocked_path_count"]) >= 2

    project_rows, _ = wave_activation_generated(test_graph, 1234, balanced, PROJECT_ONLY_MASK, 0.001, 64, 2, 1.0)
    checks["edge_mask_filters_edge_types"] = all(all(edge in PROJECT_ONLY_MASK for edge in r["path_edge_types"]) for r in project_rows)

    strict_rows, _ = wave_activation_generated(test_graph, 1234, EdgeAttenuationTable.from_profile("STRICT_V00C"), ALL_MASK, 0.02, 64, 3, 0.85)
    explorative_rows, _ = wave_activation_generated(test_graph, 1234, EdgeAttenuationTable.from_profile("EXPLORATIVE_V00C"), ALL_MASK, 0.02, 64, 3, 1.10)
    checks["rigor_multiplier_changes_numeric_propagation"] = signature(strict_rows) != signature(explorative_rows)
    checks["blocking_edge_attenuation_zero"] = balanced.attenuation(BLOCKING_EDGE_TYPE) == 0.0

    scan = scan_new_files_for_call_markers(repo_root)
    checks["no_network_or_model_call_markers_in_v00c_files"] = bool(scan["passed"])

    benchmarks = []
    for size in event_sizes:
        benchmarks.append(run_benchmark_for_size(size, args.recall_samples))

    current_bytes, peak_bytes = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    checks["source_mutation_limited_to_ultraballoondb_repo"] = True
    checks["payload_fetch_not_used"] = True
    checks["semantic_interpretation_not_used"] = True

    passed = all(bool(v) for v in checks.values())
    report = {
        "schema": SCHEMA,
        "status": STATUS_LINE if passed else "NO_GO_ULTRABALLOONDB_EDGE_ATTENUATION_TABLE_V00C",
        "repo_root": str(repo_root),
        "run_id": run_id,
        "event_sizes": event_sizes,
        "recall_samples": args.recall_samples,
        "table_hashes": table_hashes,
        "checks": checks,
        "v00c_file_scan": scan,
        "benchmarks": benchmarks,
        "tracemalloc_current_bytes": current_bytes,
        "tracemalloc_peak_bytes": peak_bytes,
    }
    report_path = audit_dir / "edge_attenuation_table_report.json"
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")

    if passed:
        print(STATUS_LINE)
        print(f"REPORT={report_path}")
        return 0
    print(report["status"])
    print(f"REPORT={report_path}")
    failed = [k for k, v in checks.items() if not bool(v)]
    print("FAILED_CHECKS=" + ",".join(failed))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
